### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by tekstrand**
Cleaning up the code to make it more readable. No functionality changes yet, didn't want to overwhelm it in one giant PR

### CODE REVIEW

**Comment by mistic100** [comment]
@tekstrand do you want to take over the project ?

**Comment by tekstrand** [comment]
@mistic100 I am fine with that, sure

**Comment by mistic100** [comment]
Ok what is your username on piwigo.org forum ? (required to publish extensions)

**Comment by tekstrand** [comment]
@mistic100 it's `tekstrand` same as Github here

**Pull request merged**
